# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

contact_list = [
  [ "Tracy", "Beck" ],
  [ "Gina", "Myers" ],
  [ "Felicia", "Brady" ],
  [ "Ed", "Tyler" ],
  [ "Cornelius", "Nguyen" ],
  [ "Daisy", "Barton" ],
  [ "Domingo", "Young" ],
  [ "Tanya", "Berry" ],
  [ "Kellie", "Vega" ],
  [ "Woodrow", "Greene" ],
  [ "Isaac", "Jimenez" ],
  [ "Lorenzo", "Todd" ],
  [ "Salvador", "Rios" ],
  [ "Erick", "Reed" ],
  [ "Nina", "Brock" ],
  [ "Alfred", "Baker" ],
  [ "Marty", "French" ],
  [ "Esther", "Douglas" ],
  [ "Jeremiah", "Cummings" ],
  [ "Shelia", "Gill" ],
  [ "Ivan", "Hampton" ],
  [ "Amos", "Barker" ],
  [ "Johnnie", "Lawson" ],
  [ "Willie", "Webster" ],
  [ "Edgar", "Abbott" ],
  [ "Isabel", "Warren" ],
  [ "Gerardo", "Lawrence" ],
  [ "Nelson", "Hicks" ],
  [ "Lillie", "Morton" ],
  [ "Sara", "Byrd" ],
  [ "Derrick", "Riley" ],
  [ "Janis", "Griffith" ],
  [ "Juana", "Porter" ],
  [ "Lamar", "Johnston" ],
  [ "Irving", "Sanders" ],
  [ "Phillip", "Scott" ],
  [ "Doyle", "Cortez" ],
  [ "Alberto", "Park" ],
  [ "Betsy", "Barber" ],
  [ "Tricia", "Day" ],
  [ "Audrey", "Spencer" ],
  [ "Dianne", "Curry" ],
  [ "Elaine", "Nichols" ],
  [ "Meghan", "Campbell" ],
  [ "Yvette", "Hansen" ],
  [ "Clarence", "Foster" ],
  [ "Leah", "Sparks" ],
  [ "Jenny", "Bailey" ],
  [ "Devin", "Stone" ],
  [ "Miguel", "Mitchell" ],
  [ "Lora", "Clark" ],
  [ "Bernard", "Hernandez" ],
  [ "Louise", "Vaughn" ],
  [ "Melba", "Morris" ],
  [ "Jasmine", "Walton" ],
  [ "Darla", "Fleming" ],
  [ "Rita", "Taylor" ],
  [ "Sam", "Daniel" ],
  [ "Courtney", "Butler" ],
  [ "Juan", "Adkins" ],
  [ "Erin", "Griffin" ],
  [ "Ronald", "Norton" ],
  [ "Dorothy", "Owens" ],
  [ "Sophie", "Lloyd" ],
  [ "Gertrude", "Harrington" ],
  [ "Lola", "Fitzgerald" ],
  [ "Rodney", "Rice" ],
  [ "Omar", "Manning" ],
  [ "Helen", "Lyons" ],
  [ "Austin", "Boyd" ],
  [ "Alexis", "Bennett" ],
  [ "Flora", "Welch" ],
  [ "Minnie", "Reeves" ],
  [ "Saul", "Franklin" ],
  [ "Erma", "Hanson" ],
  [ "Cheryl", "Alvarez" ],
  [ "Darlene", "Chapman" ],
  [ "Earl", "Williamson" ],
  [ "Tara", "Waters" ],
  [ "Bob", "Bowen" ],
  [ "Valerie", "Watts" ],
  [ "Jessica", "Austin" ],
  [ "Orlando", "Williams" ],
  [ "Josephine", "West" ],
  [ "Drew", "Mendez" ],
  [ "Willard", "Reese" ],
  [ "Margie", "Wilson" ],
  [ "Darrel", "Stanley" ],
  [ "Noah", "Andrews" ],
  [ "Marcella", "Mcdaniel" ],
  [ "Mike", "Fletcher" ],
  [ "Jerald", "Walker" ],
  [ "Andrew", "Bridges" ],
  [ "Kathryn", "Doyle" ],
  [ "Cathy", "Lynch" ],
  [ "Betty", "Carroll" ],
  [ "Jennie", "Quinn" ],
  [ "Carol", "Elliott" ],
  [ "Nadine", "Ortiz" ],
  [ "Casey", "Arnold" ],
]

contact_list.each do |first_name, last_name|
  Contact.create( first_name: first_name, last_name: last_name)
end
